name: eclass
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  facebook_audience_network: ^1.0.1
  intl_phone_number_input: ^0.7.0+2
  package_info: ^2.0.2
  upi_india: ^3.0.1
  share: ^2.0.4
  flutter_carousel_slider: ^1.0.9
  flutter_facebook_auth: ^4.3.4+2
  cashfree_pg: ^2.0.10+30
  wakelock: ^0.6.1+2
  flutterwave_payment: ^0.0.4+2
  sqflite: ^2.0.2+1
  path: ^1.8.1
  flutter_zoom_sdk: ^1.1.0+4
  url_launcher: ^6.1.4
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.3
  firebase_analytics: ^9.1.12
  shared_preferences: ^2.0.15
  translator: ^0.1.7
  vimeo_player_flutter: ^0.0.3+2
  loading_overlay: ^0.3.0
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_pdfviewer: ^20.2.36-beta
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  percent_indicator: ^4.2.2
  path_morph: ^1.0.1
  fading_edge_scrollview: ^3.0.0
  http: ^0.13.1
  razorpay_flutter: ^1.3.0
  fluttertoast: ^8.0.9
  page_transition: ^2.0.9
  flutter_secure_storage: ^5.0.2
  flutter_swiper: ^1.1.6
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  file_picker: ^4.6.1
  flutter_paystack: ^1.0.5+1
  youtube_player_flutter: ^8.1.0
  shimmer: ^2.0.0
  dio: ^4.0.0
  flutter_widget_from_html: ^0.8.5
  http_auth: ^1.0.1
  auto_size_text: ^3.0.0
  html_unescape: ^2.0.0
  sticky_headers: ^0.3.0+2
  paytm: ^3.0.1
  youtube_player_iframe: ^2.3.0
  flutter_inappwebview: ^5.4.3+7
  better_player: 0.0.83
#  better_player:
#    path: local/better_player-0.0.79
  webview_flutter: ^3.0.4
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  google_sign_in: ^5.3.3
  flutter_downloader: ^1.8.0+1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  audioplayers: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/placeholder/
    - assets/i18n/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mada
      fonts:
        - asset: fonts/Mada-Regular.ttf
          weight: 400
        - asset: fonts/Mada-Bold.ttf
          weight: 700
        - asset: fonts/Mada-SemiBold.ttf
          weight: 600
        - asset: fonts/Mada-Medium.ttf
          weight: 500
        - asset: fonts/Mada-Light.ttf
          weight: 300
        - asset: fonts/Mada-Black.ttf
          weight: 800
    - family: icomoon
      fonts:
        - asset: assets/custom_icons/custom-icons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages